name = "ChannelSimulations"
uuid = "5367ffc7-6744-43e0-8170-7f8348ae4d71"
authors = ["Simone Silvestri"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
